name: Auto Fix
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
      - name: Auto fix code
        run: |
          black .
          isort .
      - name: Commit changes
        run: |
          git config --global user.email "96681219+XtomiX@users.noreply.github.com"
          git config --global user.name "XtomiX"
          git add .
          git commit -m "Auto fix code"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.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 }}
