name: Python Auto Fix

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pyupgrade

    - name: Run pylint
      run: |
        pylint *.py

    - name: Run pyupgrade
      run: |
        pyupgrade --py39-plus *.py
