name: Auto-Fix Python Code with Latest Version

on:
  push:
    branches: [main]

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Change to latest Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Auto-format Python code
      run: |
        pip install black
        black .

    - name: Commit and push changes
      run: |
        git config --global user.email "96681219+XtomiX@users.noreply.github.com"
        git config --global user.name "XtomiX"
        git add .
        git commit -m "Auto-format Python code"
        git push origin HEAD:main
