name: Git Commit

on:
  push:
    branches: [main]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.name "XtomiX"
          git config --global user.email "96681219+XtomiX@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Commit message"
          git push origin main
