name: Auto Fix Syntax

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Auto Fix Syntax
        run: |
          black . --exclude=venv
          isort .

      - name: Commit Changes
        run: |
          git config --global user.name "XtomiX"
          git config --global user.email "96681219+XtomiX@users.noreply.github.com"
          git commit -am "Auto fix syntax" --allow-empty
