name: Auto Fix
on: [push]
jobs:
  auto_fix_by_tomi_setiawan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort autoflake
      - name: Auto Fix
        run: | 
          black --exclude=venv .
          isort --skip-glob='**/venv/**' .
          find . -name '*.txt' -type f -exec autoflake --in-place --remove-unused-variables --remove-all-unused-imports --ignore-init-module-imports {} +
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .
      - name: Code Analysis
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto Fix"
