name: Python Auto Fix

on:
  push:
    branches: [ main ]

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Auto Fix
      run: |
        black .
        isort .

    - name: Commit changes
      run: |
        git config --global user.name 'XtomiX'
        git config --global user.email '96681219+XtomiX@users.noreply.github.com'
        git commit -a -m "Auto fix"
        git push
